---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kube-to-status
  namespace: github
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-to-status
subjects:
  - kind: ServiceAccount
    name: kube-to-status
    namespace: github
roleRef:
  kind: ClusterRole
  name: kube-to-status
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-to-status
  namespace: github
  labels:
    app: kube-to-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-to-status
  template:
    metadata:
      labels:
        app: kube-to-status
    spec:
      containers:
        - name: kubernetes-status
          image: decathlon/kubernetes-status-to-github:0.7.0
          # Args to add if you have to go through a proxy:
          # args:
          #  - -Dhttps.proxyHost=your-proxy.corp/cpù
          #  - -Dhttps.proxyPort=3128
          #  - -Dhttp.nonProxyHosts=172.20.0.1|kubernetes|kubernetes.default.svc.cluster.local
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: kube-to-status
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          volumeMounts:
            - mountPath: /workspace/config
              name: kube-to-status
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
      serviceAccountName: kube-to-status
      volumes:
        - name: kube-to-status
          configMap:
            name: kube-to-status
---

